import type { GroupMetrics } from "./metrics";

function esc(s: string) {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function pct(x: number) {
  return `${(x * 100).toFixed(1)}%`;
}

export function buildHtmlReport(args: {
  title: string;
  accuracy: number;
  dpd: number;
  eod: number;
  riskLevel: string;
  riskMessage: string;
  groupMetrics: GroupMetrics[];

  // ✅ NEW (optional metadata)
  datasetName?: string;
  modelName?: string;
  threshold?: number | null;
  generatedAt?: string;
}) {

  // destructure and give defaults
  const {
    title,
    accuracy,
    dpd,
    eod,
    riskLevel,
    riskMessage,
    groupMetrics,
    datasetName,
    modelName,
    threshold,
    generatedAt,
  } = args;

  const rows = groupMetrics
    .map(
      (g) => `
      <tr>
        <td>${esc(g.group)}</td>
        <td>${g.count}</td>
        <td>${pct(g.selectionRate)}</td>
        <td>${pct(g.tpr)}</td>
        <td>${pct(g.fpr)}</td>
        <td>${pct(g.fnr)}</td>
      </tr>
    `
    )
    .join("");

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${esc(title)} — Fairness Report</title>
  <style>
    body { font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial; margin: 24px; color: #111; }
    h1 { margin: 0 0 8px; }
    .muted { color: #555; margin: 0 0 16px; }
    .grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 12px; margin: 16px 0 16px; }
    .card { border: 1px solid #e5e7eb; border-radius: 14px; padding: 12px; background: #fafafa; }
    .k { font-size: 12px; color: #666; margin: 0; }
    .v { font-size: 20px; font-weight: 650; margin: 6px 0 0; }
    .risk { border: 1px solid #e5e7eb; border-radius: 14px; padding: 12px; margin: 12px 0; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    th, td { border-top: 1px solid #e5e7eb; padding: 10px; font-size: 14px; text-align: left; }
    th { color: #444; background: #f9fafb; }
    .note { font-size: 12px; color: #666; margin-top: 14px; }
  </style>
</head>
<body>
  <h1>${esc(title)} — Fairness Report</h1>
  <div class="card" style="margin-top:12px;">
    <p class="k">Audit Metadata</p>
    <p class="v" style="font-size:14px; font-weight:400;">
      <b>Dataset:</b> ${esc(datasetName || "Not specified")}<br/>
      <b>Model:</b> ${esc(modelName || "Not specified")}<br/>
      <b>Threshold:</b> ${threshold !== null && threshold !== undefined ? threshold.toFixed(2) : "N/A"}<br/>
      <b>Generated:</b> ${esc(generatedAt || new Date().toISOString())}
    </p>
  </div>

  <p class="muted">Generated by EthicAI Audit (educational tool).</p>

  <div class="grid">
    <div class="card">
      <p class="k">Accuracy</p>
      <p class="v">${pct(accuracy)}</p>
    </div>
    <div class="card">
      <p class="k">Demographic Parity Difference (DPD)</p>
      <p class="v">${pct(dpd)}</p>
    </div>
    <div class="card">
      <p class="k">Equal Opportunity Difference (EOD)</p>
      <p class="v">${pct(eod)}</p>
    </div>
  </div>

  <div class="risk">
    <p class="k">Fairness Risk Rating</p>
    <p class="v">${esc(riskLevel)} Risk</p>
    <p style="margin:8px 0 0; color:#333;">${esc(riskMessage)}</p>
  </div>

  <h2 style="margin-top:18px;">Metrics by Group</h2>
  <table>
    <thead>
      <tr>
        <th>Group</th>
        <th>Count</th>
        <th>Selection Rate</th>
        <th>TPR</th>
        <th>FPR</th>
        <th>FNR</th>
      </tr>
    </thead>
    <tbody>
      ${rows}
    </tbody>
  </table>

  <p class="note">
    Note: This report is illustrative and based on the provided data. Real-world deployments should use domain requirements, stakeholder input, and additional validation.
  </p>
</body>
</html>`;
}